#!/usr/bin/env bash

# Quit on ^C.
trap exit INT

while read -r
do
    echo "$REPLY"
    echo " $REPLY" | t2m "$@" | aplay -q -r 44100 -f S16_LE
	#     ^--- Hackaround for power saving crap of some soundcards.
done
