#!/usr/bin/env python3

from argparse import ArgumentParser
from random import choice
from os import getenv
from pipes import quote
from string import ascii_lowercase, digits
from subprocess import DEVNULL, PIPE, Popen
from sys import stdin
from time import sleep

phonetic_alphabet = {
    'a': 'Alpha',
    'b': 'Bravo',
    'c': 'Charlie',
    'd': 'Delta',
    'e': 'Echo',
    'f': 'Foxtrot',
    'g': 'Golf',
    'h': 'Hotel',
    'i': 'India',
    'j': 'Juliet',
    'k': 'Kilo',
    'l': 'Lima',
    'm': 'Mike',
    'n': 'November',
    'o': 'Oscar',
    'p': 'Papa',
    'q': 'Quebec',
    'r': 'Romeo',
    's': 'Sierra',
    't': 'Tango',
    'u': 'Uniform',
    'v': 'Victor',
    'w': 'Whiskey',
    'x': 'X-ray',
    'y': 'Yankee',
    'z': 'Zulu',
    #'.': 'Full stop',       # espeak builtins
    ',': 'Comma',
    #':': 'Colon',
    '?': 'Question mark',
    '\'': 'Apostrophe',
    '-': 'Hyphen',
    #'/': 'Fraction bar',
    '(': 'Left-hand bracket',
    ')': 'Right-hand bracket',
    '"': 'Quotation mark',
    #'=': 'Double hyphen',
    #'+': 'Addition sign',
    #'@': 'Commercial at',
    ';': 'Semicolon',
    '_': 'Underscore',
}

charpool = list(ascii_lowercase) + list(digits) + ['.', ',', ':', '?',
        '\'', '-', '/', '(', ')', '"', '=', '+', '@', ';', '_']

def morse(s):
    # Like morsetrainer_linewise, this extra space is a hackaround for
    # power saving modes of some soundcards.
    cmd = 'echo " "{} | t2m -c 0.5 | aplay -qr 44100 -f S16_LE'.format(quote(s))
    player = Popen(cmd, shell=True)
    player.communicate()

def say(s, is_line=False):
    language = getenv('ESPEAK_LANG', 'en')
    espeak = Popen(['espeak', '-s', '120', '-v', language],
                   stdin=PIPE, stderr=DEVNULL)

    if is_line:
        espeak.stdin.write(s.encode())
    else:
        for i in s:
            espeak.stdin.write(
                '{}, {}. '.format(
                    i.upper(), phonetic_alphabet.get(i, '')
                ).encode()
            )

    espeak.communicate()

if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_argument('-n', '--no-sleep', action='store_true')
    parser.add_argument('-p', '--packs', type=int, default=1)
    parser.add_argument('-s', '--stdin', action='store_true')
    args = parser.parse_args()

    while True:
        if args.stdin:
            s = stdin.readline().strip()
            if not s:
                break
        else:
            s = ''
            for i in range(args.packs):
                s += choice(charpool)

        for i in range(2):
            morse(s)
            if not args.no_sleep:
                sleep(1)
            say(s, is_line=args.stdin)
            print(s)
            if not args.no_sleep:
                sleep(1)
        if not args.no_sleep:
            sleep(2)
