#!/usr/bin/env python3

from argparse import ArgumentParser
from random import choice
from os import getenv
from pipes import quote
from string import ascii_lowercase, digits
from subprocess import DEVNULL, PIPE, Popen
from sys import stdin
from time import sleep

phonetic_alphabet = {
    'a': 'Alpha',
    'b': 'Bravo',
    'c': 'Charlie',
    'd': 'Delta',
    'e': 'Echo',
    'f': 'Foxtrot',
    'g': 'Golf',
    'h': 'Hotel',
    'i': 'India',
    'j': 'Juliet',
    'k': 'Kilo',
    'l': 'Lima',
    'm': 'Mike',
    'n': 'November',
    'o': 'Oscar',
    'p': 'Papa',
    'q': 'Quebec',
    'r': 'Romeo',
    's': 'Sierra',
    't': 'Tango',
    'u': 'Uniform',
    'v': 'Victor',
    'w': 'Whiskey',
    'x': 'X-ray',
    'y': 'Yankee',
    'z': 'Zulu',
    '.': 'Full stop',
    ',': 'Comma',
    ':': 'Colon',
    '?': 'Question mark',
    '\'': 'Apostrophe',
    '-': 'Hyphen',
    '/': 'Fraction bar',
    '(': 'Left-hand bracket',
    ')': 'Right-hand bracket',
    '"': 'Quotation mark',
    '=': 'Double hyphen',
    '+': 'Addition sign',
    '@': 'Commercial at',
    ';': 'Semicolon',
    '_': 'Underscore',
}

charpool = []
charpool += list(ascii_lowercase)
charpool += list(digits) 
charpool += ['.', ',', ':', '?', '\'', '-', '/', '(', ')', '"', '=', '+', '@', ';', '_']

def morse(s, f, w):
    # Like morsetrainer_linewise, this extra space is a hackaround for
    # power saving modes of some soundcards.
    cmd = 'echo " "{} | t2m -c 0.5 -f {} -w {} | aplay -qr 44100 -f S16_LE'.format(
        quote(s),
        f,
        w,
    )
    player = Popen(cmd, shell=True)
    player.communicate()

def say(s, is_line=False):
    language = getenv('ESPEAK_LANG', 'en')
    espeak = Popen(['espeak', '-s', '120', '-v', language],
                   stdin=PIPE, stderr=DEVNULL)

    if is_line:
        espeak.stdin.write(s.encode())
    else:
        phonetic = []
        for i in s:
            phonetic.append(phonetic_alphabet.get(i, i))
        espeak.stdin.write((', '.join(phonetic) + '.').encode())

    espeak.communicate()

if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_argument('-f', '--freq', default=900, type=int)
    parser.add_argument('-n', '--no-sleep', action='store_true')
    parser.add_argument('-p', '--packs', type=int, default=1)
    parser.add_argument('-r', '--repetitions', type=int, default=2)
    parser.add_argument('-s', '--stdin', action='store_true')
    parser.add_argument('-w', '--wpm', type=int, default=20)
    args = parser.parse_args()

    while True:
        if args.stdin:
            s = stdin.readline().strip()
            if not s:
                break
        else:
            s = ''
            for i in range(args.packs):
                s += choice(charpool)

        for i in range(args.repetitions):
            morse(s, args.freq, args.wpm)
            if not args.no_sleep:
                sleep(1)
            say(s, is_line=args.stdin)
            print(s)
            if not args.no_sleep:
                sleep(1)
        if not args.no_sleep:
            sleep(2)
